services:
  db:
    image: postgres:16-alpine
    container_name: spotifer-postgres
    environment:
      POSTGRES_DB: spotifer
      POSTGRES_USER: spotifer
      POSTGRES_PASSWORD: spotifer
    ports:
      - "5432:5432"
    volumes:
      - spotifer_db_data:/var/lib/postgresql/data

  app:
    build: .
    command: ["java","-jar","app.jar","--server.address=0.0.0.0"]
    container_name: spotifer-app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/spotifer
      SPRING_DATASOURCE_USERNAME: spotifer
      SPRING_DATASOURCE_PASSWORD: spotifer
      SPRING_PROFILES_ACTIVE: docker
      APP_AUTH_POST_LOGIN_REDIRECT: http://localhost:5173/

    ports:
      - "8080:8080"

volumes:
  spotifer_db_data:
