spring:
  application:
    name: spotifer
#  datasource:
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:spotifer}
#    username: ${DB_USER:postgres}
#    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
#      ddl-auto: validate
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
  security:
    oauth2:
      client:
        provider:
          spotify:
            token-uri: https://accounts.spotify.com/api/token
            authorization-uri: https://accounts.spotify.com/authorize
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id
        registration:
          spotify-client-cred:
            provider: spotify
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: user-read-email
          spotify-auth-code:
            provider: spotify
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/spotify-auth-code"
            client-name: Spotify (Auth Code)
            scope:
              - user-read-email
              - playlist-read-private
              - user-library-read
              - user-top-read
              - user-read-recently-played
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

app:
  jwt:
    issuer: spotifer
    access-ttl-min: 15
    secret: ${APP_JWT_SECRET:dev-secret-please-change}
  auth:
    post-login-redirect: http://127.0.0.1:5173/app
    cookie-domain: 127.0.0.1
  top:
    freshness-hours: 24
  recently-played:
    freshness-minutes: 20

server:
  port: 8080
  address: 127.0.0.1
  # DEBUG
  error:
    include-message: ALWAYS
    include-binding-errors: ALWAYS
    include-stacktrace: ALWAYS

# DEBUG
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: INFO
    pl.mlodyg.spotifer: DEBUG
